resolvers += Resolver.bintrayRepo("guizmaii", "sbt-plugins")

addSbtPlugin("io.get-coursier"           % "sbt-coursier"        % "1.0.3")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.5.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.2.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.8")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"             % "0.3.7")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.6.0")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.4.1")
addSbtPlugin("com.guizmaii.sbt"          % "sbt-elm"             % "0.2.5")
