addSbtPlugin("io.get-coursier"           % "sbt-coursier"  % "1.0.3")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"   % "0.4.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.0.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.6")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"       % "0.3.6")
addSbtPlugin("org.scoverage"             % "sbt-scoverage" % "1.5.1")
addSbtPlugin("io.spray"                  % "sbt-revolver"  % "0.9.1")
